name: Build Bicep File and Deploy
on: workflow_dispatch
permissions:
  contents: read
  id-token: write
jobs:
  build-whatif:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Bicep Build
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: ./deploy/bicep/deploy-appService.bicep
          outputFilePath: azuredeploy.json
      - name: Upload Bicep Output
        uses: actions/upload-artifact@v3
        with:
          name: bicep-output
          path: azuredeploy.json
      - name: Azure Login with OIDC
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Preview changes
        uses: Azure/deployment-what-if-action@v1.0.0
        with:
          subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroup: '${{ vars.RESOURCE_GROUP_NAME }}'
          templateFile: ./deploy/bicep/deploy-appService.bicep # main.bicep
          parametersFile: ./deploy/bicep/deploy.appService.parameters.json
  deploy-dev:
    needs: build-whatif
    environment:
      name: DEV
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Azure Login with OIDC
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy Infrastructure
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: '${{ vars.RESOURCE_GROUP_NAME }}'
          template: ./deploy/bicep/deploy-appService.bicep
          parameters: ./deploy/bicep/deploy.appService.parameters.json
