name: Build Bicep File and Upload
on: [workflow_dispatch, push]
permissions:
  contents: read
  id-token: write
jobs:
  build-whatif:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Bicep Build
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: ./deploy/deploy-appService.bicep
          outputFilePath: azuredeploy.json
      - name: Upload Bicep Output
        uses: actions/upload-artifact@v3
        with:
          name: bicep-output
          path: azuredeploy.json
      - name: Azure Login with OIDC
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Preview changes
        uses: Azure/deployment-what-if-action@v1.0.0
        with:
          subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroup: '${{ vars.RESOURCE_GROUP_NAME }}'
          templateFile: azuredeploy.json # main.bicep
          parametersFile: ./deploy/deploy.appService.parameters.json
